#!/bin/sh
#rm META-INF/MANIFEST.MF
#echo "Manifest-Version: 1.0
#Main-Class: run.GuiGeneration" > META-INF/MANIFEST.MF
#cat ../mFoot >> META-INF/MANIFEST.MF
rm -f ./SplineGenerator/Applied/*.class
rm -f ./SplineGenerator/Applied/LegacyVersions/*.class
rm -f ./SplineGenerator/Splines/*.class
rm -f ./run/*.class
javac ./run/*.java -Xlint:unchecked
javac ./SplineGenerator/Applied/*.java -Xlint:unchecked
javac ./SplineGenerator/Applied/LegacyVersions/*.java -Xlint:unchecked
javac ./SplineGenerator/Splines/*.java -Xlint:unchecked
jar cmvf0 META-INF/MANIFEST.MF ../SwerveLib.jar $(find . -name '*.class') > garboFile
#jar umvf0 META-INF/MANIFEST.MF2 ../SwerveLib.jar ./SplineGenerator/Applied/*.class > garboFile
#jar umvf0 META-INF/MANIFEST.MF2 ../SwerveLib.jar ./SplineGenerator/Splines/*.class > garboFile
#jar umvf0 META-INF/MANIFEST.MF2 ../SwerveLib.jar ./SplineGenerator/Splines/*.class > garboFile
java -jar ../SwerveLib.jar /home/ibrahim/in.txt /home/ibrahim/out.txt
rm garboFile
rm -f ./SplineGenerator/Applied/*.class
rm -f ./SplineGenerator/Applied/LegacyVersions/*.class
rm -f ./SplineGenerator/Splines/*.class
rm -f ./run/*.class
